[package]
name = "tunneltimeclient"
version = "0.1.0"
authors = ["Quinten Palmer <quintenpalmer@gmail.com>"]

[dependencies]
tunneltimecore = {path = "../tunneltimecore"}
serde = "1.0.0"
serde_json = "1.0.0"

futures = "0.1"
hyper = "0.11"
tokio-core = "0.1"
